# Numpy Complete tutorial 
Numpy is a general-purpose array-processing package used to do scientific computiong in python faster to handle data and takes less space than traditional practices

In [2]:
import numpy as np

In [3]:
myarr=np.array([3,6,7,2782664,9],np.int8)
# general array making

In [4]:
myarr 
# so here we will get int8 number instead of 4th element of myarr as we declared size allowed for number as np.int8 
# so to solve this either don't write int8 or something
# writing int8 or something is useful when we have to put condition on input numbers

array([  3,   6,   7, -56,   9], dtype=int8)

In [5]:
myarr[0,1]
# error coz we don't have anything on 0,1

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [7]:
myarr.shape

(5,)

In [8]:
myarr.dtype
# gives u what data type we are using right now

dtype('int8')

In [9]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[3,5,6,7,3]])

In [12]:
a.shape

(3, 5)

In [13]:
newarr=np.random.rand(3,5)
newarr
# syntax to create array of random numbers

array([[0.40014937, 0.11561223, 0.54914274, 0.82447505, 0.82627596],
       [0.84017766, 0.6827774 , 0.28423871, 0.3305819 , 0.99694864],
       [0.14158828, 0.90040823, 0.90423889, 0.33573328, 0.15404378]])

In [14]:
# Array creation : 1: Conversions from other python structures
listarr=np.array([[1,2,3],[4,5,6],[0,3,1]])
listarr.dtype

dtype('int32')

In [15]:
listarr.shape

(3, 3)

In [16]:
listarr.size

9

In [ ]:
# Method2 of making arrays: 
zeroes=np.zeros((2,5))
zeroes

In [17]:
arange=np.arange(15)
arange
# NumPy arange () is one of the array creation routines based on numerical ranges

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# if we want any array equally distributed in any number of frequency we use linspace
# equally linearly spaced integers
lspace=np.linspace(1,12,5)

In [19]:
lspace

array([ 1.  ,  3.75,  6.5 ,  9.25, 12.  ])

In [20]:
# Empty : here we can make empty array of any size and it will put random numbers in it
# use is that if we already made an array and if we want to update that we can use this array using np.empty_like
emp =np.empty((4,6))
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.69120145e-306, 4.45064003e-308, 4.45059334e-308],
       [8.90097448e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306, 6.23057689e-307],
       [8.45597329e-307, 8.45559303e-307, 8.06613040e-308,
        6.89810244e-307, 1.22387550e-307, 2.22522596e-306]])

In [21]:
emp_like=np.empty_like(lspace)
emp_like
# in this way we have updated empty array for any future work

array([ 1.  ,  3.75,  6.5 ,  9.25, 12.  ])

In [22]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(45, 45)

In [26]:
arr=np.arange(99)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
(99,)


In [27]:
arr=arr.reshape(3,33)
# for reshaping we need same sized array inputs 
# for eg earlier we made 99 sized 1d array so we can make 3*33 sized array only not 3*31
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
# to convert any array into 1d array we have ravel function
arr=arr.ravel()
print(arr.shape)
arr

(99,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
# Numpy axis: count starts from 0 , axis0 towards row and axis1 works in columnns
x=[[1,2,3],[4,5,6],[7,8,9]]

In [30]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar.sum(axis=0)
# so we can see sum as 12 of 1st column 15 as sum of 2nd column so it works row-wise

array([12, 15, 18])

In [32]:
ar.sum(axis=1)

array([ 6, 15, 24])

***Numpy attributes***

In [33]:
ar.T
# makes array transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
for item in ar.flat:
#     ar.flat is A 1-D iterator over the array.
    print(item)

1
2
3
4
5
6
7
8
9


In [35]:
one=np.array([1,2,3,4])

In [36]:
print(one.argmax())
# gives index of maximum element
print(one.argmin())
print(one.argsort()) # gives in ascending order

3
0
[0 1 2 3]


In [37]:
ar=np.array([[1,2,3],[4,5,6],[6,7,8]])
ar2=np.array([[1,2,3],[4,5,6],[6,7,8]])
ar3=ar*ar2
ar3

array([[ 1,  4,  9],
       [16, 25, 36],
       [36, 49, 64]])

In [38]:
ar4=ar+ar2
ar4
# but if we directly make addition of list then we will get extended list not addition at that indices

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [12, 14, 16]])

In [39]:
a=np.sqrt(ar3)
a


array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

In [40]:
# how nupy takes less space
import sys

In [41]:
py_ar=[0,4,55,2]
np_ar=np.array(py_ar)

In [42]:
sys.getsizeof(1) * len(py_ar)

112

In [43]:
np_ar.itemsize*np_ar.size

16

# Hope this basic tutorial of numpy works out for you!! Rest learning never stops and any use case needs to be googled for more knowledge!!